# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Question.create([
  { :answer => "I am, Me, And only myself!", :data => {"type"=>"Multiple choice", "question"=>"Who is awesome?", "options"=>[{"value"=>"I am"}, {"value"=>"Me"}, {"value"=>"And only myself!"}]}, :quiz_id => 1, :created_at => "2013-05-23 20:35:21", :updated_at => "2013-05-23 20:35:21" },
  { :answer => "Only one answer", :data => {"type"=>"Multiple choice", "question"=>"Q1", "options"=>[{"value"=>"Only one answer"}]}, :quiz_id => 2, :created_at => "2013-05-24 13:40:35", :updated_at => "2013-05-25 10:08:02" },
  { :answer => "Also true, This is true", :data => {"type"=>"Multiple choice", "question"=>"Q2", "options"=>[{"value"=>"Also true"}, {"value"=>"This is false"}, {"value"=>"This is true"}]}, :quiz_id => 2, :created_at => "2013-05-24 13:42:16", :updated_at => "2013-05-25 10:12:49" },
  { :answer => "Singer, Sir", :data => {"type"=>"Multiple choice", "question"=>"Who was Elton John?", "options"=>[{"value"=>"Singer"}, {"value"=>"King"}, {"value"=>"Sir"}]}, :quiz_id => 2, :created_at => "2013-05-24 21:01:25", :updated_at => "2013-05-25 10:08:21" },
  { :answer => "Kerttu Kivisikk", :data => {"options"=>[{"value"=>"Elvis"}, {"value"=>"Dijkstra"}, {"value"=>"Kerttu Kivisikk"}], "type"=>"Multiple choice", "question"=>"Who is the best person in the world?"}, :quiz_id => 3, :created_at => "2013-05-26 15:43:16", :updated_at => "2013-05-26 15:43:16" },
  { :answer => "Everyone is!, I am!, You are!", :data => {"options"=>[{"value"=>"I am!"}, {"value"=>"You are!"}, {"value"=>"Everyone is!"}], "type"=>"Multiple choice", "question"=>"Who is awesome?"}, :quiz_id => 3, :created_at => "2013-05-26 15:43:52", :updated_at => "2013-05-26 15:43:52" }
], :without_protection => true )


Quiz.create([
  { :name => "MegaQuiz", :summary => "Hello", :created_at => "2013-05-24 13:40:19", :updated_at => "2013-05-24 13:40:19" },
  { :name => "Superb Test Quiz", :summary => "Fantastic!", :created_at => "2013-05-26 11:53:36", :updated_at => "2013-05-26 11:53:36" }
], :without_protection => true )


User.create([
  { :provider => "facebook", :uid => "1198871700", :name => "Karl Aksel Puulmann", :oauth_token => "CAAIiGz42kCMBALkZAWOSrSwaQjLeouZBHsQhWZCNbBpxVsH0vLKMV8Y94QRJ0UYOUOB5Qr8VZA1bsXIaiTtcevn6Ld5aZBHZAtLZBcV8SF8VUVXUR8Rt9cxkwrVNoep18PJ84KwAuoNA2t7hj1x3ad4WsyeP5MrjZBcZD", :oauth_expires_at => "2013-05-26 17:00:00", :created_at => "2013-05-22 14:07:19", :updated_at => "2013-05-26 15:49:11" }
], :without_protection => true )


